### ISSUE TITLE
Pastebin scraping API Removed

### ISSUE THREAD

**Issue by w1ld3r** [kevthehermit/PasteHunter#112] opened 2020-04-15 00:41 UTC
https://pastebin.com/api_scraping_faq
This page has been removed!
So, is it still possible to scrap pastebin using PatseHunter ?

**Comment by Plazmaz** [comment] 2020-04-15 02:49
Hi, I'm investigating it. It sure looks a lot like pastebin quietly killed their scraping API.

**Comment by Plazmaz** [comment] 2020-04-15 03:16
I have confirmed that this page has been deleted. I have also been able to confirm that existing whitelisted IP addresses currently have access still. I strongly suggest you bring this up with pastebin support. I am currently trying to get into contact with them and am quite unhappy if this is intentional. As a side note, they also recently removed their search bar and apparently limited the access of free accounts. I am concerned that this is intentional, but will report back if I hear anything from them or notice the page has returned.

**Comment by Plazmaz** [comment] 2020-04-15 03:50
It's official, Pastebin has confirmed they've removed their scraping API.

**Comment by kevthehermit** [comment] 2020-04-15 07:39
This is a strange move by pastebin forcing us to go to manual scrape as I doubt they have blocked malware being uploaded at the same time

**Comment by kevthehermit** [comment] 2020-04-15 12:05
I was just pointed at this - https://github.com/Mikts/pbwrap

It may help us get around the scraping API and still use an authenticated account to avoid ratelimiting / other detections?

**Comment by x1n5h3n** [comment] 2020-04-15 21:09
Thanks for your replies, it's really disappointing from pastebin. Do you think it will be possible for new Pro users to request Pastebin for IP whitelisting ? Maybe, in the next few days, they will remove the currently whitelisted @IP ...

**Comment by aparedero** [comment] 2020-04-24 17:46
Pastebin: This is a great example of how a website have dug its own grave. From several pastes each 10s to single paste each 3-5 minutes. Thank you for let us know.

**Comment by dmille6** [comment] 2020-04-28 23:26
looks like the API page is back up.. they have just changed from a whitelist to a token/dev key... am i missing something?

**Comment by aparedero** [comment] 2020-04-28 23:30
@dmille6 Yep, it looks that https://pastebin.com/doc_scraping_api page is back again, but the site has lost too much activity these days...

**Comment by Plazmaz** [comment] 2020-04-29 14:53
It's actually not that pastebin is being used less. They've restricted the API to only pastes that have syntax highlighting enabled:
https://twitter.com/pastebin/status/1254775693637902337

**Comment by H4ckW0lf** [comment] 2020-05-12 16:29
Hi guys!  

I would like to know if possible Add flag to pass/read a list of proxies to avoid IP ban/throttle for free users ?

**Comment by Plazmaz** [comment] 2020-05-14 20:39
Hi, so I've considered it. I think the truth is I really don't want to play that cat and mouse game with them. I do plan on adding proxy support because I want to eventually expand this project to more general scraping and analysis, but my energy for side projects is pretty limited currently, so I have not been as active with developing new features.

**Comment by secbug** [comment] 2020-07-27 20:07
Uuuuuh. Folks. Is the scraping API back up for anyone else? I currently have access via my pro account.

**Comment by Plazmaz** [comment] 2020-07-27 20:17
@secbug partial access was restored at some point but was heavily limited last time I checked (50-60 new pastes per minute). You seeing normal speed again?

**Comment by secbug** [comment] 2020-07-27 20:27
For public pastes I'm seeing a lagged paste update, yeah. Only by a couple minutes though, and I'm keeping to their recommended paste speeds (1 list-all every minute with fetching of data from the pastes). They do warn that this delay happens now though, saying: Due to caching, items listed here are shown with a 2 minute delay.

**Comment by secbug** [comment] 2020-07-27 20:28
I also see the site itself being used a loooot less. As of posting this there is a 45+ minute gap between recent public pastes.

**Comment by secbug** [comment] 2020-07-27 20:40
I now saw above your post, and you are correct. It's the stupid lack of syntax highlighting limiting us PRO account users. Welp. Quite sorry for the waste of time I may have caused. 
To quote Pastebin: 

> Our Scraping API is only available for "PRO" members, and only for those who have their IP whitelisted. “PRO” accounts are enabled with Scraping API and to collect only records with syntax highlighting. Enterprise API offers more robust access, including the removal of this limitation and for commercial purposes with additional features. Please contact -insert sales email- for more information.

**Comment by Plazmaz** [comment] 2020-07-28 00:33
Yep, and no problem, I already kinda expected that was still the case. Sadly, I have yet to hear from anyone who successfully got this restriction lifted, and have talked to a handful of other researchers about it. It seems like the "removal of restriction for research" offer is a purely fictional promise from what I can tell. I have some thoughts on where we're headed with this project, but current world events have effectively drained my ability to build out new features, as I alluded to earlier. For the time being I'll continue to do my best to support our other sources and this crippled version pastebin, and hopefully I can get back to adding additional value outside of pastebin at some point.

**Comment by dsetzer** [comment] 2020-08-02 22:04
It would probably be a violation of the terms but I'm sure there are plenty of people including myself who pay monthly for the pro membership and who have full access to the official scraping api https://pastebin.com/doc_scraping_api who could setup a relay api to provide access but I'm sure pastebin would notice the excessive usage for that account and block it.

It's also true what @secbug has said, I have also noticed that the site is used way less now since pastebin removed the search feature from the site. But I guess it is to be expected because before it was removed a lot of people would go there specifically to leak files and information knowing that it would then be easily found and made available to everyone by search engines and anyone who types a simple query in the search box. with no way to search or find even the public pastes older than one day nobody has any reason to leak anything anymore. I don't know what pastebin is thinking removing this when they should know that almost their entire user base is made up of either people wanting to leak information or people wanting to find that leaked information.. they don't offer any other benefits for why anyone would want to use them over the million other services out there with better features than they offer for a paste storing service

**Comment by Plazmaz** [comment] 2020-08-03 04:24
FWIW people with access to the official API do not have the same level of access before this change was made.

**Comment by Plazmaz** [comment] 2020-10-31 07:40
Going to close this issue, as I think we've sufficiently discussed the change, have made our stance pretty clear, and pastebin scraping _does_ function, although it may not be as well as before. Ongoing changes around errors are being tracked in #116.

**Closed by Plazmaz** 2020-10-31 07:40 UTC
