### ISSUE TITLE
No module named common

### ISSUE THREAD

**Issue by lotr1** [kevthehermit/PasteHunter#121] opened 2020-11-30 17:42 UTC
Issue that was resolved for pastebin in latest release is present for ixio.  Also slexi turning up an error.

INFO:pastehunter-cli:Fetching paste list from pastehunter.inputs.pastebin
ERROR:pastehunter-cli:Unable to fetch list from pastehunter.inputs.ixio: No module named 'common'
DEBUG:pastehunter-cli:Found New pastebin.com paste cd7EYRfA
INFO:pastehunter-cli:Fetching paste list from pastehunter.inputs.slexy
DEBUG:pastehunter-cli:Found New pastebin.com paste ms5dFefT
DEBUG:pastehunter-cli:Found New pastebin.com paste DGj49vYz
DEBUG:pastehunter-cli:Found New pastebin.com paste 3W9kQg4h
DEBUG:pastehunter-cli:Found New pastebin.com paste ZZ8F42ms
DEBUG:pastehunter-cli:Processing Finished for ZZ8F42ms in 0.2962474822998047 seconds
DEBUG:pastehunter-cli:Found New pastebin.com paste 5TDiSqnv
DEBUG:pastehunter-cli:Processing Finished for ms5dFefT in 0.2962024211883545 seconds
DEBUG:pastehunter-cli:Processing Finished for 3W9kQg4h in 0.30004453659057617 seconds
DEBUG:pastehunter-cli:Processing Finished for cd7EYRfA in 0.31461143493652344 seconds
DEBUG:pastehunter-cli:Processing Finished for DGj49vYz in 0.31210803985595703 seconds
DEBUG:pastehunter-cli:Found New pastebin.com paste DJig5Cr5
DEBUG:pastehunter-cli:Processing Finished for 5TDiSqnv in 0.25513339042663574 seconds
DEBUG:pastehunter-cli:Processing Finished for DJig5Cr5 in 0.24974608421325684 seconds
ERROR:pastehunter-cli:Unable to fetch list from pastehunter.inputs.slexy: HTTPSConnectionPool(host='slexy.org', port=443): Max retries exceeded with url: /recent (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0150e2b668>, 'Connection to slexy.org timed out. (connect timeout=10)'))
DEBUG:pastehunter-cli:Writing History
INFO:pastehunter-cli:Added 7 Items to the queue
INFO:pastehunter-cli:Sleeping for 60 Seconds

**Comment by Plazmaz** [comment] 2020-12-03 06:46
Ack, I missed that, sorry! Shouldn't have messed with imports for the unit tests.

The error with Slexy is one of three things:
1. A connection issue
2. A large slexy paste that would take too long to download
3. An issue with slexy
I'm guessing it's the second case, meaning that a paste took more than ten seconds to download. To fix this, I've made the timeout configurable and slightly increased it. There was also an edge case where short retry-after values led to a short timeout due to a bug. All of this should be resolved by 89018f090f0f04ab4046736faa26e9c8091ce809 which will be released as 1.4.2 once the build finishes :slightly_smiling_face:

**Comment by Plazmaz** [comment] 2020-12-03 06:47
Closing this, you're welcome to re-open it if you encounter regressions in 1.4.2

**Closed by Plazmaz** 2020-12-03 06:47 UTC

**Comment by Hell0Steve** [comment] 2024-01-09 13:31
Still getting the error for slexy
