### ISSUE TITLE
Connect to the docker?

### ISSUE THREAD

**Issue by slthomason** [kevthehermit/PasteHunter#46] opened 2018-10-17 16:52 UTC
Something isn't working when I try to run it.  I want to trouble-shoot this, but I can't figure out how to connect to the docker and see what is going wrong.  Is there some way to see some output logs or something?  My Kibana just shows this:

![image](https://user-images.githubusercontent.com/1905522/47102733-57323880-d1f2-11e8-9c45-78c5cf1e875a.png)

**Comment by kovacsbalu** [comment] 2018-10-17 21:05
hi @slthomason, can you please describe your setup?

**Comment by slthomason** [comment] 2018-10-17 21:15
So pastehunter isn't starting.  I have narrowed it down to this:
root@pastehunter:/usr/src/pastehunter# python pastehunter.py
Traceback (most recent call last):
  File "pastehunter.py", line 13, in <module>
    from queue import queue
ImportError: No module named queue

Based off this, 
https://stackoverflow.com/questions/33432426/importerror-no-module-named-queue
I tried upper and lowercase q on queue, but no luck.  Is there a pip package we are missing?

**Comment by slthomason** [comment] 2018-10-17 21:30
So to run with python3 I have to use pip3?

Yes - it seems that "out of the box" the docker stuff isn't running correctly.  Could it be the missing comma referred to in #45?  Did that get fixed and pushed so we can pull working?

Thanks!

**Comment by slthomason** [comment] 2018-10-17 21:51
I think I am close to getting the docker to start up ... attached are my files changes:

[pastehunter.zip](https://github.com/kevthehermit/PasteHunter/files/2489410/pastehunter.zip)

**Comment by gn0sys** [comment] 2018-10-17 22:43
Hi @slthomason 

I am not familiar with the Docker integration side of things but here's what I did to ensure I got pastehunter running:

1. Apt-get install python3-dev
2. Apt install python3-pip
3. pip3 install -U setuptools
4. Apt-get install yara
5. Apt-get install git
6. Apt-get install openjdk-11-jdk
7. Git clone yara-python from VirusTotal 
8. Wget installation of Elasticsearch from website
9. Wget installation of Kibana from website
10. Git clone PasteHunter
11. cd to active dir PasteHunter is in; pip3 install -r requirements.txt
12. Nano settings.json.sample and enable the desired output rendering and append the missing punctuation (',') to 300 and save.

**Comment by slthomason** [comment] 2018-10-17 22:46
Thanks.  It would be super slick if we could get the docker piece working.
I will use this and keep hacking at it.

Spencer

**Comment by kovacsbalu** [comment] 2018-10-18 13:33
@slthomason 
You can run each service with docker-compose. Now I fixed in my PR #49 
First copy `settings.json.sample` as `settings.json`
then `docker-compose up`

**Comment by slthomason** [comment] 2018-10-18 15:57
@kovacsbalu - Thx!  I will give those a try. 

I did a pull request #50 that I think resolves some other issues.

**Comment by gn0sys** [comment] 2018-10-18 19:32
You might want to try using Kite and see if that will do the trick.

**Comment by kovacsbalu** [comment] 2018-10-18 20:05
@slthomason can you please provide more details about docker build and run. All log details, not a part of it.
Maybe the problem is in your pastehunter config. Try to run without ELK and let see the logs....

**Comment by kovacsbalu** [comment] 2018-10-23 19:08
Yes, I mean log from docker.
So after you built you can run bash inside pastehunter docker.
`docker run -it <img name maybe pastehunter> bash`
Now you are in your container and you can run pastehunter with `python3 pastehunter.py`
Do you copied settings.json.sample as settings.json??

**Comment by slthomason** [comment] 2018-10-24 15:44
Yes, here is an example of my settings.json.

I can't get as far as running:

docker run -it <img name maybe pastehunter> bash

Because like the screenshots show the docker-compose up comes up, and
terminates in seconds.  I can't keep the docker running in time to connect
to it and see what is failing.  How do I tell the docker-compose to stay up
so that I can connect?

**Comment by kovacsbalu** [comment] 2018-11-05 11:39
Did you run pastehunter image alone (without composer)?
You should not run with composer (for debugging) so you dont need to tell 'stay up'.

**Comment by kevthehermit** [comment] 2019-01-23 19:53
Assuming this is resolved thanks to all who supported.

**Closed by kevthehermit** 2019-01-23 19:53 UTC
